# Generated by Django 4.1.7 on 2023-05-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_pricelist_productgroup_product_orderedproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='companytype',
            options={'verbose_name': 'Тип компании', 'verbose_name_plural': 'Типы компаний'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='UID',
        ),
    ]
