# Generated by Django 4.1.7 on 2023-06-20 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_company_options_alter_companytype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedproduct',
            options={'verbose_name': 'Заказанное изделие', 'verbose_name_plural': 'Заказанные изделия'},
        ),
        migrations.AlterModelOptions(
            name='pricelist',
            options={'verbose_name': 'Прайс', 'verbose_name_plural': 'Прайсы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Изделие', 'verbose_name_plural': 'Изделия'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'verbose_name': 'Группа изделий', 'verbose_name_plural': 'Группы изделий'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pricelist',
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.company', verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=None, null=True, verbose_name='Стоимость')),
                ('pricelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.pricelist', verbose_name='Прайс')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.product', verbose_name='Изделие')),
            ],
            options={
                'verbose_name': 'Стоимость изделий',
                'verbose_name_plural': 'Стоимости изделий',
            },
        ),
    ]
