# Generated by Django 4.1.7 on 2023-07-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_orderedproduct_options_alter_pricelist_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPrice',
            new_name='PricelistsProducts',
        ),
    ]
