# Generated by Django 4.1.7 on 2023-04-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]



